version: '3.5'

services:
  wolfpack-database:
    image: postgres:14.4-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - wolfpack-database